version: '3.7'

services:
  main:
    container_name: app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres_db
    image: postgres:14-alpine
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data    
networks:
  webnet:
volumes:
  pgdata:
